src/Entity/Category.php
<?php

namespace Kisphp\ArticlesBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Kisphp\Entity\FileInterface;
use Kisphp\Entity\KisphpEntityInterface;
use Kisphp\Entity\ToggleableInterface;
use Kisphp\Utils\Status;
use Kisphp\Utils\Strings;

/**
 * @ORM\Table(name="categories", options={"colate": "utf8_general_ci", "charset": "utf8"})
 * @ORM\Entity(repositoryClass="Kisphp\ArticlesBundle\Repository\CategoryRepository")
 */
class Category implements KisphpEntityInterface, ToggleableInterface
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer", options={"unsigned": true})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", options={"unsigned": true, "default": 0})
     */
    protected $id_parent = 0;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", options={"default": Kisphp\Utils\Status::ACTIVE})
     */
    protected $status = Status::ACTIVE;

    /**
     * @ORM\OneToMany(targetEntity="Article", mappedBy="category")
     */
    protected $articles;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    protected $title;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true, length=255)
     */
    protected $item_url;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true, length=255)
     */
    protected $seo_title;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true, length=255)
     */
    protected $seo_keywords;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true, length=255)
     */
    protected $seo_description;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    protected $body;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true, length=255)
     */
    protected $background_image;

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->title;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return int
     */
    public function getIdParent()
    {
        return $this->id_parent;
    }

    /**
     * @param int $id_parent
     */
    public function setIdParent($id_parent)
    {
        $this->id_parent = $id_parent;
    }

    /**
     * @return mixed
     */
    public function getArticles()
    {
        return $this->articles;
    }

    /**
     * @param mixed $articles
     */
    public function setArticles($articles)
    {
        $this->articles = $articles;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
        $this->setItemUrl($title);
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param int $status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * @param string $body
     */
    public function setBody($body)
    {
        $this->body = $body;
    }

    /**
     * @return string
     */
    public function getItemUrl()
    {
        return $this->item_url;
    }

    /**
     * @param string $item_url
     */
    public function setItemUrl($item_url)
    {
        $this->item_url = Strings::niceUrlTitle($item_url);
    }

    /**
     * @return string
     */
    public function getSeoTitle()
    {
        return $this->seo_title;
    }

    /**
     * @param string $seo_title
     */
    public function setSeoTitle($seo_title)
    {
        $this->seo_title = $seo_title;
    }

    /**
     * @return string
     */
    public function getSeoKeywords()
    {
        return $this->seo_keywords;
    }

    /**
     * @param string $seo_keywords
     */
    public function setSeoKeywords($seo_keywords)
    {
        $this->seo_keywords = $seo_keywords;
    }

    /**
     * @return string
     */
    public function getSeoDescription()
    {
        return $this->seo_description;
    }

    /**
     * @param string $seo_description
     */
    public function setSeoDescription($seo_description)
    {
        $this->seo_description = $seo_description;
    }

    /**
     * @return array
     */
    public function getBackgroundImage()
    {
        return json_decode($this->background_image, true);
    }

    /**
     * @param FileInterface $image
     */
    public function setBackgroundImage(FileInterface $image)
    {
        $this->background_image = json_encode([
            'id' => $image->getId(),
            'filename' => $image->getFilename(),
            'directory' => $image->getDirectory(),
        ]);
    }

    public function removeBackgroundImage()
    {
        $this->background_image = null;
    }
}

src/Form/CategoryForm.php
<?php

namespace Kisphp\ArticlesBundle\Form;

use Kisphp\ArticlesBundle\Entity\Category;
use Kisphp\Utils\Status;
use Kisphp\Utils\Strings;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class CategoryForm extends AbstractType
{
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'attr' => [
                'novalidate' => 'novalidate',
            ],
            'data_class' => Category::class,
        ]);

        $resolver->setRequired('categories_choices');
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title', TextType::class, [
            'constraints' => [
                new NotBlank(),
            ],
        ]);
        $builder->add('status', ChoiceType::class, [
            'expanded' => true,
            'choices' => [
                'status.active' => Status::ACTIVE,
                'status.inactive' => Status::INACTIVE,
            ],
            'attr' => [
                'class' => 'input-choice',
            ],
        ]);
        $builder->add('id_parent', ChoiceType::class, [
            'label' => 'Parent Category',
            'choices' => array_merge([
                'form.choices.no_sparent_category' => 0,
            ], $options['categories_choices']),
            'choice_label' => function($choice, $key, $value){
                $data = explode('|', $key);
                return end($data);
            },
            'empty_data' => null,
        ]);
        $builder->add('body', TextareaType::class, [
            'label' => 'Category content',
            'attr' => [
                'class' => 'html-edit',
            ],
        ]);
        $builder->add('seo_title');
        $builder->add('seo_keywords');
        $builder->add('seo_description', TextareaType::class);

        $builder->addModelTransformer(new CallbackTransformer(
            function ($entity) {
                return $this->fixEntityModel($entity);
            },
            /**
             * @param Category $entity
             */
            function ($entity) {
                return $this->fixEntityModel($entity);
            }
        ));
    }

    /**
     * @param Category $entity
     *
     * @return Category
     */
    protected function fixEntityModel(Category $entity)
    {
        if (empty($entity->getSeoTitle())) {
            $entity->setSeoTitle($entity->getTitle());
        }
        if (empty($entity->getItemUrl())) {
            $entity->setItemUrl(Strings::niceUrlTitle($entity->getTitle()));
        }

        return $entity;
    }
}

src/Controller/CategoriesController.php
<?php

namespace Kisphp\ArticlesBundle\Controller;

use Kisphp\ArticlesBundle\Form\CategoryForm;
use Kisphp\Entity\KisphpEntityInterface;
use Kisphp\FrameworkAdminBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Template()
 */
class CategoriesController extends AbstractController
{
    const SECTION_TITLE = 'section.title.categories';
    const MODEL_NAME = 'model.category';
    const ENTITY_FORM_CLASS = CategoryForm::class;
    const LISTING_TEMPLATE = '@Articles/Categories/index.html.twig';
    const EDIT_TEMPLATE = '@Articles/Categories/edit.html.twig';

    const HTML_EDITOR_ENABLED = true;
    const UPLOAD_TYPE = 'category';

    /**
     * @var array
     */
    protected $section = [
        self::EDIT_PATH => 'adm_article_categories_edit',
        self::LIST_PATH => 'adm_article_categories',
        self::ADD_PATH => 'adm_article_categories_add',
        self::STATUS_PATH => 'adm_article_categories_status',
        self::DELETE_PATH => 'adm_article_categories_delete',
    ];

    /**
     * @param Request $request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(Request $request)
    {
        $items = $this->get(static::MODEL_NAME)
            ->getCategoriesForListing()
        ;

        return $this->render(
            static::LISTING_TEMPLATE,
            [
                'section_title' => static::SECTION_TITLE . '.list',
                'items' => $items,
                'section' => $this->section,
            ]
        );
    }

    /**
     * @param Request $request
     * @param int $id category id
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function attachedBackgroundAction(Request $request, $id)
    {
        /** @var \Kisphp\ArticlesBundle\Entity\Category $entity */
        $entity = $this->get('model.category')->find($id);
        $attached = $this->getAttachedFiles($id);

        return $this->render('@Articles/Categories/background.html.twig', [
            'entity' => $entity,
            'attached' => $attached,
        ]);
    }

    /**
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function attachedBackgroundRemoveAction(Request $request)
    {
        $categoryId = $request->request->get('id');

        /** @var \Kisphp\ArticlesBundle\Entity\Category $entity */
        $entity = $this->get('model.category')->find($categoryId);

        if ($entity === null) {
            return new JsonResponse([
                'code' => 404,
            ]);
        }

        $entity->removeBackgroundImage();

        $this->get('model.category')->save($entity);

        return new JsonResponse([
            'code' => 200,
            'id_category' => $entity->getId(),
        ]);
    }

    /**
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function attachedBackgroundSetAction(Request $request)
    {
        $imageId = $request->request->get('id');
        $categoryId = $request->request->get('cat');

        /** @var \Kisphp\ArticlesBundle\Entity\Category $entity */
        $entity = $this->get('model.category')->find($categoryId);

        /** @var \Kisphp\MediaBundle\Entity\MediaFile $img */
        $img = $this->get('model.media_files')->setType('category')->find($imageId);

        if ($img === null || $entity === null) {
            return new JsonResponse([
                'code' => 404,
            ]);
        }

        $entity->setBackgroundImage($img);

        $this->get('model.category')->save($img);

        return new JsonResponse([
            'code' => 200,
            'id_category' => $entity->getId(),
            'id_image' => $img->getId(),
        ]);
    }

    /**
     * @param Request $request
     * @param KisphpEntityInterface $object
     *
     * @return \Symfony\Component\Form\FormInterface
     */
    protected function createFormObject(Request $request, $object)
    {
        $form = $this->createForm(static::ENTITY_FORM_CLASS, $object, [
            'categories_choices' => $this->get('model.category')->getCategoriesForForm(),
        ]);
        $form->handleRequest($request);

        return $form;
    }

    /**
     * @return string
     *
     * @param mixed $id
     */
    protected function getImagesEditUrl($id)
    {
        return $this->generateUrl('adm_article_categories_attached', [
            'id' => $id,
        ]);
    }

    /**
     * @param int $articleId
     *
     * @return array
     */
    protected function getAttachedFiles($articleId)
    {
        $model = $this->get('model.media_files');

        return $model->findBy([
            'id_object' => $articleId,
            'object_type' => static::UPLOAD_TYPE,
        ]);
    }
}

src/Resources/views/Categories/background.html.twig
{% extends '@FrameworkAdmin/layout.html.twig' %}

{% block section_title %}
    {{ ('title.set_background_for' | trans ~ ' <b>' ~ entity.title ~  '</b>') | raw }}
{% endblock %}

{% block box_header %}
    <a href="{{ path('adm_article_categories_edit', {id: entity.id}) }}" class="btn btn-xs btn-info"><i class="fa fa-list"></i> {{ 'btn.back_to_categories' | trans }}</a>
    <a href="#" data-id="{{ entity.id }}" class="btn btn-xs btn-danger remove-background"><i class="fa fa-list"></i> {{ 'btn.remove_background' | trans }}</a>
{% endblock %}

{% block body %}
    <div class="row" id="files-list">
        {% if attached is defined and attached | length > 0 %}
            {% for img in attached %}
                <div class="col-sm-2 col-md-2" id="row-{{ img.id }}">
                    <div id="thumb-{{ img.id }}" class="thumbnail{% if entity.backgroundImage.id is defined and entity.backgroundImage.id == img.id %} thumb-active{% endif %}" style="overflow: hidden;">
                        <img src="{{ thumb(img.directory, 200, 200, img.filename) }}" class="img-responsive" alt="{{ img.title }}" />
                        <div class="caption">
                            <p>{{ img.title }}</p>
                            <p class="img-buttons" id="img-buttons-{{ img.id }}" data-id-thumb="{{ img.id }}">
                                <a href="#" class="btn btn-info btn-xs set-background" data-image-id="{{ img.id }}" data-category-id="{{ entity.id }}" role="button">Set as background</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

src/Resources/views/Categories/edit.html.twig
{% extends '@FrameworkAdmin/components/form.html.twig' %}

{% block box_header %}
    {% if entity is defined and entity.id is defined and entity.id > 0 %}
    <a href="{{ path('adm_article_categories_attached_set_background', {id: entity.id}) }}" class="btn btn-xs btn-info"><i class="fa fa-list"></i> {{ 'btn.set_background_image' | trans }}</a>
    {% endif %}
    {{ parent() }}
{% endblock %}

src/Resources/views/Categories/index.html.twig
{% extends '@FrameworkAdmin/components/listing.html.twig' %}

{% import '@FrameworkAdmin/macros/navigation-macros.html.twig' as navBtn %}
{% import '@FrameworkAdmin/macros/table-btn-macros.html.twig' as tbl %}

{% block box_header %}
    {{ navBtn.list(path(section.list_path), 'btn.list') }}
    {{ navBtn.create(path(section.add_path), 'btn.create') }}
{% endblock %}

{% block listing_table_content %}
    <thead>
    <tr>
        <th width="200">{{ 'table.header.options' | trans }}</th>
        <th width="60">{{ 'table.header.id' | trans }}</th>
        <th>{{ 'table.header.title' | trans }}</th>
        <th width="60">{{ 'table.header.status' | trans }}</th>
    </tr>
    </thead>
    <tbody>
    {% for cat in items %}
        {% set item = cat.object %}
        <tr id="row-{{ item.id }}">
            <td>
                {{ tbl.edit(path(section.edit_path, {id: item.id})) }}
                {{ tbl.delete(item.id, path(section.delete_path)) }}
            </td>
            <td>{{ item.id }}</td>
            <td>{{ '&#8212;' | repeat(cat.level) }} <a href="{{ path(section.edit_path, {id: item.id}) }}">{{ item.title }}</a></td>
            {{ statusToggle(item, path(section.status_path)) }}
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}